package soa32.resources.notaFiscal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-02-04T11:39:08.992-02:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://resource.faturamento.soa32/", name = "NotaFiscalResourcePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface NotaFiscalResourcePortType {

    @RequestWrapper(localName = "delete", targetNamespace = "http://resource.faturamento.soa32/", className = "soa32.resources.notaFiscal.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://resource.faturamento.soa32/", className = "soa32.resources.notaFiscal.DeleteResponse")
    public void delete(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @RequestWrapper(localName = "deleteAll", targetNamespace = "http://resource.faturamento.soa32/", className = "soa32.resources.notaFiscal.DeleteAll")
    @WebMethod
    @ResponseWrapper(localName = "deleteAllResponse", targetNamespace = "http://resource.faturamento.soa32/", className = "soa32.resources.notaFiscal.DeleteAllResponse")
    public void deleteAll(
        @WebParam(name = "ids", targetNamespace = "")
        java.util.List<java.lang.Long> ids
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://resource.faturamento.soa32/", className = "soa32.resources.notaFiscal.Get")
    @WebMethod
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://resource.faturamento.soa32/", className = "soa32.resources.notaFiscal.GetResponse")
    public soa32.resources.notaFiscal.NotaFiscal get(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "list", targetNamespace = "http://resource.faturamento.soa32/", className = "soa32.resources.notaFiscal.List")
    @WebMethod
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://resource.faturamento.soa32/", className = "soa32.resources.notaFiscal.ListResponse")
    public java.util.List<soa32.resources.notaFiscal.NotaFiscal> list();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://resource.faturamento.soa32/", className = "soa32.resources.notaFiscal.Create")
    @WebMethod
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://resource.faturamento.soa32/", className = "soa32.resources.notaFiscal.CreateResponse")
    public java.lang.Long create(
        @WebParam(name = "entity", targetNamespace = "")
        soa32.resources.notaFiscal.NotaFiscal entity
    );
}
