package soa32.resources.notaFiscal;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-02-04T11:39:09.036-02:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "NotaFiscalResource", 
                  wsdlLocation = "http://dls98:8181/faturamento/api/notas-fiscais?wsdl",
                  targetNamespace = "http://resource.faturamento.soa32/") 
public class NotaFiscalResource extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://resource.faturamento.soa32/", "NotaFiscalResource");
    public final static QName NotaFiscalResourcePort = new QName("http://resource.faturamento.soa32/", "NotaFiscalResourcePort");
    static {
        URL url = null;
        try {
            url = new URL("http://dls98:8181/faturamento/api/notas-fiscais?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NotaFiscalResource.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://dls98:8181/faturamento/api/notas-fiscais?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NotaFiscalResource(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NotaFiscalResource(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotaFiscalResource() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotaFiscalResource(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotaFiscalResource(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotaFiscalResource(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns NotaFiscalResourcePortType
     */
    @WebEndpoint(name = "NotaFiscalResourcePort")
    public NotaFiscalResourcePortType getNotaFiscalResourcePort() {
        return super.getPort(NotaFiscalResourcePort, NotaFiscalResourcePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotaFiscalResourcePortType
     */
    @WebEndpoint(name = "NotaFiscalResourcePort")
    public NotaFiscalResourcePortType getNotaFiscalResourcePort(WebServiceFeature... features) {
        return super.getPort(NotaFiscalResourcePort, NotaFiscalResourcePortType.class, features);
    }

}
