package soa32.resources.produto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-02-04T11:47:52.804-02:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://resource.faturamento.soa32/", name = "ProdutoResourcePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ProdutoResourcePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://resource.faturamento.soa32/", className = "soa32.resources.produto.Get")
    @WebMethod
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://resource.faturamento.soa32/", className = "soa32.resources.produto.GetResponse")
    public soa32.resources.produto.Produto get(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "list", targetNamespace = "http://resource.faturamento.soa32/", className = "soa32.resources.produto.List")
    @WebMethod
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://resource.faturamento.soa32/", className = "soa32.resources.produto.ListResponse")
    public java.util.List<soa32.resources.produto.Produto> list();
}
