package soa32.resources.produto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-02-04T11:47:52.847-02:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "ProdutoResource", 
                  wsdlLocation = "http://dls98:8181/faturamento/api/produtos?wsdl",
                  targetNamespace = "http://resource.faturamento.soa32/") 
public class ProdutoResource extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://resource.faturamento.soa32/", "ProdutoResource");
    public final static QName ProdutoResourcePort = new QName("http://resource.faturamento.soa32/", "ProdutoResourcePort");
    static {
        URL url = null;
        try {
            url = new URL("http://dls98:8181/faturamento/api/produtos?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProdutoResource.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://dls98:8181/faturamento/api/produtos?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProdutoResource(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProdutoResource(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProdutoResource() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProdutoResource(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProdutoResource(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProdutoResource(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ProdutoResourcePortType
     */
    @WebEndpoint(name = "ProdutoResourcePort")
    public ProdutoResourcePortType getProdutoResourcePort() {
        return super.getPort(ProdutoResourcePort, ProdutoResourcePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProdutoResourcePortType
     */
    @WebEndpoint(name = "ProdutoResourcePort")
    public ProdutoResourcePortType getProdutoResourcePort(WebServiceFeature... features) {
        return super.getPort(ProdutoResourcePort, ProdutoResourcePortType.class, features);
    }

}
